//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTRINHDUHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTRINHDUHOC()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.DANGKYLOTRINHs = new HashSet<DANGKYLOTRINH>();
            this.HOSOKHACHHANGs = new HashSet<HOSOKHACHHANG>();
        }
    
        public int MALT { get; set; }
        public string TENLT { get; set; }
        public string MOTALT { get; set; }
        public string MOTACHITIET { get; set; }
        public Nullable<int> THOIGIANHOC { get; set; }
        public Nullable<decimal> CHIPHI { get; set; }
        public Nullable<int> MATDH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKYLOTRINH> DANGKYLOTRINHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSOKHACHHANG> HOSOKHACHHANGs { get; set; }
        public virtual TRUONGDAIHOC TRUONGDAIHOC { get; set; }
    }
}
