//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTRUNGTAMDUHOCEntities : DbContext
    {
        public QUANLYTRUNGTAMDUHOCEntities()
            : base("name=QUANLYTRUNGTAMDUHOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DANGKYLOTRINH> DANGKYLOTRINHs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HOCBONG> HOCBONGs { get; set; }
        public virtual DbSet<HOSOKHACHHANG> HOSOKHACHHANGs { get; set; }
        public virtual DbSet<HOSOVISA> HOSOVISAs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LICHHENTUVAN> LICHHENTUVANs { get; set; }
        public virtual DbSet<LOTRINHDUHOC> LOTRINHDUHOCs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NUOC> NUOCs { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<TRUONGDAIHOC> TRUONGDAIHOCs { get; set; }
    }
}
